//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MichrazolEntities : DbContext
    {
        public MichrazolEntities()
            : base("name=MichrazolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<CitiesAreas> CitiesAreas { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<PasswordResetRequest> PasswordResetRequest { get; set; }
        public virtual DbSet<ProductForSale> ProductForSale { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<SuggestedPrices> SuggestedPrices { get; set; }
        public virtual DbSet<Tender> Tender { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
