//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedPrices
    {
        public int Id { get; set; }
        public int TenderId { get; set; }
        public int UserProductId { get; set; }
        public Nullable<int> SuggestedPrice { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual ProductForSale ProductForSale { get; set; }
        public virtual Tender Tender { get; set; }
    }
}
